ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: Game
    before: cd terraforming-mars
    init: >
      npm install &&
      npm run build
    command: >
      npm run start &&
      gp await-port 8080 &&
      echo "TODO start game"
  - name: Bot
    command: "TODO start bot"
