ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - name: Server
    before: cd terraforming-mars
    init: >
      npm install &&
      npm run build
    command: >
      npm run start &&
      npm run start
  - name: Game
    command: >
      gp await-port 8080 &&
      sleep 2 &&
      node start-game $(gp url 8080)
  - name: Bot
    init: npm install
    command: node play-bot
